import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DndProviders } from "@/providers/dnd-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { NavMenu } from "@/components/nav-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <DndProviders>
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavMenu />
            {children}
          </ThemeProvider>
        </body>
      </DndProviders>
    </html>
  );
}
