import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { DndProviders } from '@/providers/dnd-provider'
import { ThemeProvider } from '@/providers/theme-provider'
import { NavMenu } from '@/components/shared/nav-menu'
import { cn } from '@/lib/utils'
import { StatusProvider } from '@/hooks/use-statuses'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kanban Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={cn([''], inter.className)}>
        <DndProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StatusProvider>
              <NavMenu />
              {children}
            </StatusProvider>
          </ThemeProvider>
        </DndProviders>
      </body>
    </html>
  )
}
